// Package kardinal_manager_rest_types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.1-0.20240604070534-2f0ff757704b DO NOT EDIT.
package kardinal_manager_rest_types

// Defines values for ResponseType.
const (
	ERROR   ResponseType = "ERROR"
	INFO    ResponseType = "INFO"
	WARNING ResponseType = "WARNING"
)

// ResponseInfo defines model for ResponseInfo.
type ResponseInfo struct {
	Code    uint32       `json:"code"`
	Message string       `json:"message"`
	Type    ResponseType `json:"type"`
}

// ResponseType defines model for ResponseType.
type ResponseType string

// VirtualService defines model for VirtualService.
type VirtualService struct {
	Name string `json:"name"`
}

// NotOk defines model for NotOk.
type NotOk = ResponseInfo

// PostVirtualServicesJSONRequestBody defines body for PostVirtualServices for application/json ContentType.
type PostVirtualServicesJSONRequestBody = VirtualService
