import { GoogleTagManager } from "@next/third-parties/google";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

import Footer from "@/components/Footer";
import Main from "@/components/Main";
import Modal from "@/components/Modal";
import Nav from "@/components/Nav";
import SegmentAnalytics from "@/components/SegmentAnalytics";
import { ModalProvider } from "@/context/ModalContext";
import { VotingProvider } from "@/context/VotingContext";

import StyledComponentsRegistry from "../lib/registry";

import "react-responsive-carousel/lib/styles/carousel.min.css";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "block",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link
          rel="apple-touch-icon"
          href="/apple-icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <SegmentAnalytics />
      <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_ID!} />
      <body className={inter.className}>
        <ModalProvider>
          <VotingProvider>
            <StyledComponentsRegistry>
              <Nav />
              <Main>{children}</Main>
              <Footer />
              <Modal />
            </StyledComponentsRegistry>
          </VotingProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
