import { GoogleTagManager } from "@next/third-parties/google";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { Suspense } from "react";
import Script from "next/script";

import Footer from "@/components/Footer";
import Main from "@/components/Main";
import Modal from "@/components/Modal";
import Nav from "@/components/Nav";
import SegmentAnalytics from "@/components/SegmentAnalytics";
import { CalculatorProvider } from "@/context/CalculatorContext";
import { ModalProvider } from "@/context/ModalContext";
import { VotingProvider } from "@/context/VotingContext";

import StyledComponentsRegistry from "../lib/registry";

import "react-responsive-carousel/lib/styles/carousel.min.css";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "block",
  variable: "--font-sans",
  weight: ["300", "400", "500", "600", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link
          rel="apple-touch-icon"
          href="/apple-icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link rel="icon" href="/favicon.ico" sizes="any" />

        {/* Canonical Tag */}
        <link rel="canonical" href="https://kardinal.dev/" />
      
        {/* Google Tag (gtag.js) */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-NSSL0D7NJ3"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-NSSL0D7NJ3');
          `}
        </Script>
        <meta
          name="google-site-verification"
          content="TyEWPOTqy29q6e2c_YerchK788fJdKbRYW42BnBywmY"
        />
      </head>
      <SegmentAnalytics />
      <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_ID!} />
      <body className={inter.className}>
        <ModalProvider>
          <VotingProvider>
            <Suspense>
              <CalculatorProvider>
                <StyledComponentsRegistry>
                  <Nav />
                  <Main>{children}</Main>
                  <Footer />
                  <Modal />
                </StyledComponentsRegistry>
              </CalculatorProvider>
            </Suspense>
          </VotingProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
