/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/cluster-resources": {
    /** Cluster resource definition */
    get: {
      parameters: {
        query?: {
          /** @description The namespace for which to retrieve the cluster resources */
          namespace?: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": components["schemas"]["ClusterResources"];
          };
        };
        default: components["responses"]["NotOk"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ResponseInfo: {
      type: components["schemas"]["ResponseType"];
      message: string;
      /** Format: uint32 */
      code: number;
    };
    /** @enum {string} */
    ResponseType: "ERROR" | "INFO" | "WARNING";
    ClusterResources: {
      services?: unknown[];
      deployments?: unknown[];
      virtual_services?: unknown[];
      destination_rules?: unknown[];
      gateway?: unknown;
    };
  };
  responses: {
    /** @description Unexpected error */
    NotOk: {
      content: {
        "application/json": components["schemas"]["ResponseInfo"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
