// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version 2.1.0 DO NOT EDIT.
package types

import (
	compose "github.com/compose-spec/compose-go/types"
)

// ClusterTopology defines model for ClusterTopology.
type ClusterTopology struct {
	Edges []Edge `json:"edges"`
	Nodes []Node `json:"nodes"`
}

// DevFlowSpec defines model for DevFlowSpec.
type DevFlowSpec struct {
	DockerCompose *[]compose.ServiceConfig `json:"docker-compose,omitempty"`
	ImageLocator  *string                  `json:"image-locator,omitempty"`
	ServiceName   *string                  `json:"service-name,omitempty"`
}

// Edge defines model for Edge.
type Edge struct {
	// Label Label for the edge.
	Label *string `json:"label,omitempty"`

	// Source The identifier of the source node of the edge.
	Source string `json:"source"`

	// Target The identifier of the target node of the edge.
	Target string `json:"target"`
}

// Node defines model for Node.
type Node struct {
	// Id Unique identifier for the node.
	Id string `json:"id"`

	// Label Label for the node.
	Label *string `json:"label,omitempty"`
}

// ProdFlowSpec defines model for ProdFlowSpec.
type ProdFlowSpec struct {
	DockerCompose *[]compose.ServiceConfig `json:"docker-compose,omitempty"`
}

// GetTopologyParams defines parameters for GetTopology.
type GetTopologyParams struct {
	// Namespace The namespace for which to retrieve the topology
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// PostDeployJSONRequestBody defines body for PostDeploy for application/json ContentType.
type PostDeployJSONRequestBody = ProdFlowSpec

// PostFlowCreateJSONRequestBody defines body for PostFlowCreate for application/json ContentType.
type PostFlowCreateJSONRequestBody = DevFlowSpec

// PostFlowDeleteJSONRequestBody defines body for PostFlowDelete for application/json ContentType.
type PostFlowDeleteJSONRequestBody = ProdFlowSpec
