// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version 2.1.0 DO NOT EDIT.
package types

import (
	v1alpha3 "istio.io/client-go/pkg/apis/networking/v1alpha3"
	v1beta1 "istio.io/client-go/pkg/apis/security/v1beta1"
	appsv1 "k8s.io/api/apps/v1"
	appv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	net "k8s.io/api/networking/v1"
	gateway "sigs.k8s.io/gateway-api/apis/v1"
)

// Defines values for ResponseType.
const (
	ERROR   ResponseType = "ERROR"
	INFO    ResponseType = "INFO"
	WARNING ResponseType = "WARNING"
)

// ClusterResources defines model for ClusterResources.
type ClusterResources struct {
	AuthorizationPolicies *[]v1beta1.AuthorizationPolicy `json:"authorization_policies,omitempty"`
	Deployments           *[]appsv1.Deployment           `json:"deployments,omitempty"`
	DestinationRules      *[]v1alpha3.DestinationRule    `json:"destination_rules,omitempty"`
	EnvoyFilters          *[]v1alpha3.EnvoyFilter        `json:"envoy_filters,omitempty"`
	Gateways              *[]gateway.Gateway             `json:"gateways,omitempty"`
	HttpRoutes            *[]gateway.HTTPRoute           `json:"http_routes,omitempty"`
	Ingresses             *[]net.Ingress                 `json:"ingresses,omitempty"`
	Services              *[]corev1.Service              `json:"services,omitempty"`
	StatefulSets          *[]appv1.StatefulSet           `json:"stateful-sets,omitempty"`
	VirtualServices       *[]v1alpha3.VirtualService     `json:"virtual_services,omitempty"`
}

// ResponseInfo defines model for ResponseInfo.
type ResponseInfo struct {
	Code    uint32       `json:"code"`
	Message string       `json:"message"`
	Type    ResponseType `json:"type"`
}

// ResponseType defines model for ResponseType.
type ResponseType string

// Uuid defines model for uuid.
type Uuid = string

// NotOk defines model for NotOk.
type NotOk = ResponseInfo
