apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    kardinal.dev.service/shared: "true"
    kardinal.dev.service/plugins: "postgres-seed-plugin"


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-seed-plugin
  annotations:
    kardinal.dev.service/plugin-definition: |
      - name: github.com/kurtosis-tech/postgres-seed-plugin
        type: stateful
        servicename: postgres-seed-plugin
        args:
                  seed_script: |
                    --  create the table
                    CREATE TABLE IF NOT EXISTS public.items(
                        id bigserial PRIMARY KEY,
                        created_at TIMESTAMP WITH TIME ZONE,
                        updated_at TIMESTAMP WITH TIME ZONE,
                        deleted_at TIMESTAMP WITH TIME ZONE,
                        user_id TEXT,
                        product_id TEXT,
                        quantity INTEGER
                    );
  
                    INSERT INTO public.items (id, created_at, updated_at, deleted_at, user_id, product_id, quantity) 
                    VALUES (1, '2024-08-02 13:02:07.656104 +00:00', '2024-08-02 13:02:07.656104 +00:00', null, '0494c5e0-dde0-48fa-a6d8-f7962f5476bf', '66VCHSJNUP', 1);
  
                    INSERT INTO public.items (id, created_at, updated_at, deleted_at, user_id, product_id, quantity) 
                    VALUES (2, '2024-08-02 13:02:10.891407 +00:00', '2024-08-02 13:02:10.891407 +00:00', null, '0494c5e0-dde0-48fa-a6d8-f7962f5476bf', '2ZYFJ3GM2N', 1);
  
                    INSERT INTO public.items (id, created_at, updated_at, deleted_at, user_id, product_id, quantity) 
                    VALUES (3, '2024-08-02 13:03:10.891407 +00:00', '2024-08-02 13:02:10.891407 +00:00', null, '0494c5e0-dde0-48fa-a6d8-f7962f5476bf', '2ZYFJ3GM2N', ${last_insert_quantity:-1});
  
                    -- Set the sequence to the correct value after inserting records
                    SELECT setval('public.items_id_seq', (SELECT MAX(id) FROM public.items));
                  db_name: "cart"
                  db_user: "postgresuser"
                  db_password: "postgrespass"