// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version 2.1.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	. "github.com/kurtosis-tech/kardinal/libs/manager-kontrol-api/api/golang/types"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Cluster resource definition
	// (GET /tenant/{uuid}/cluster-resources)
	GetTenantUuidClusterResources(ctx echo.Context, uuid Uuid) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetTenantUuidClusterResources converts echo context to params.
func (w *ServerInterfaceWrapper) GetTenantUuidClusterResources(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "uuid" -------------
	var uuid Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", ctx.Param("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTenantUuidClusterResources(ctx, uuid)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/tenant/:uuid/cluster-resources", wrapper.GetTenantUuidClusterResources)

}

type NotOkJSONResponse ResponseInfo

type GetTenantUuidClusterResourcesRequestObject struct {
	Uuid Uuid `json:"uuid"`
}

type GetTenantUuidClusterResourcesResponseObject interface {
	VisitGetTenantUuidClusterResourcesResponse(w http.ResponseWriter) error
}

type GetTenantUuidClusterResources200JSONResponse ClusterResources

func (response GetTenantUuidClusterResources200JSONResponse) VisitGetTenantUuidClusterResourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTenantUuidClusterResourcesdefaultJSONResponse struct {
	Body       ResponseInfo
	StatusCode int
}

func (response GetTenantUuidClusterResourcesdefaultJSONResponse) VisitGetTenantUuidClusterResourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Cluster resource definition
	// (GET /tenant/{uuid}/cluster-resources)
	GetTenantUuidClusterResources(ctx context.Context, request GetTenantUuidClusterResourcesRequestObject) (GetTenantUuidClusterResourcesResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetTenantUuidClusterResources operation middleware
func (sh *strictHandler) GetTenantUuidClusterResources(ctx echo.Context, uuid Uuid) error {
	var request GetTenantUuidClusterResourcesRequestObject

	request.Uuid = uuid

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTenantUuidClusterResources(ctx.Request().Context(), request.(GetTenantUuidClusterResourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTenantUuidClusterResources")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTenantUuidClusterResourcesResponseObject); ok {
		return validResponse.VisitGetTenantUuidClusterResourcesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8SWz27jNhDGX8WY9iiLyeZS+BY0u6lRNAkcpz0sgoArj+TZSCQ7HHrXDfTuBUX5Tza2",
	"EhRt9yTZ/Gb4m4+SZp6gsI2zBo14mDyB06wbFOTuVwi0iNcF+oLJCVkDE7i7m16MbDmSJY4YvQ1cIGRA",
	"cc1pWUIGRjcIkxSfAeOfgRgXMBEOmIEvltjomFjWLuq8MJkK2raNYu+s8dgBXFm5fow3hTWCRuKtdq6m",
	"QkcY9dlHoqe9jD8yljCBH9SuLpVWvZr1qaemtGmzbwoz+NVhIbgYIbNliJI+OOb+uQ5ekGd9zckwtg5Z",
	"KP3SQZaW6a+O7sHZmop+hQSb7ubruLLjvu7V6ScUfZqf74fdxKg1ZDvlmBpnuSu+N7YPhCwZPgHyQjYn",
	"q4qa0Mi4sso9Vko78spjEZhkrTZRsayeQDPrNXROuNqum81zcBBXO+dXp/nFVjoMmeQ7xseffCTUjlRc",
	"UqtjJF7IJAc51IP26dot9Vl+sQuZhRpf8y5Fvc08g/LF8iOZSm0DD1GjWdn1Q0n15t0ZJn4f5R869feg",
	"rbTgF70+DtoL8st0HWastqIe0VPl8/64+8VxOnY6euxLEffANgi+TvXLfH4zi9L/gYtMxej9AJVByadJ",
	"NcxjUA6+Dc9O7SCER15RMcBQWMbVaX6bdMMYSXuQJC4dZRAtWIZ67HH4GxE5eu0tvv6N+AefiBWxBF0/",
	"vGrL9n37PUW8yZ//4pXb/WE/fcZCYhXP2tGLVlLYBcZrabnREpspGTl7B9tEZAQr5JipQe91hQc66kb9",
	"tsY4j9rUhDcd+2NKsNsjS2T3AwXN+y3RhCZmeD+bXc8gg+nVh2vI4I/z2dX06nIvxX7/p94NIanj2m/a",
	"6ApZ/WqNsK1H5zdTyGCF7FPTPs1P8pO4u3VotCOYwFn3Vzq9zkslaLQR9RQHklYVqY+Peb+RV9g9A/EI",
	"ukYyXcAELlHmXehdoMWL9p89G5c+HvZ4J1HdONTefzPjvDs5+dcmnBeIB6ac21AU6H0Z6tGGI7XdUoda",
	"ju2wRVZpJutGo9A0mtcw2UxG23FwtMCSDHU7ZiC6iv7AS9/v27Zt/w4AAP//RSXnmYQKAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
