/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/flow/create": {
    post: {
      /** @description Create a dev flow */
      requestBody: {
        content: {
          "application/json": components["schemas"]["DevFlowSpec"];
        };
      };
      responses: {
        /** @description Dev flow creation status */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
    };
  };
  "/flow/delete": {
    post: {
      /** @description Delete dev flow (revert back to prod only) */
      requestBody: {
        content: {
          "application/json": components["schemas"]["ProdFlowSpec"];
        };
      };
      responses: {
        /** @description Dev flow creation status */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
    };
  };
  "/deploy": {
    post: {
      /** @description Deploy a prod only cluster */
      requestBody: {
        content: {
          "application/json": components["schemas"]["ProdFlowSpec"];
        };
      };
      responses: {
        /** @description Dev flow creation status */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
    };
  };
  "/topology": {
    get: {
      parameters: {
        query?: {
          /** @description The namespace for which to retrieve the topology */
          namespace?: string;
        };
      };
      responses: {
        /** @description Topology information */
        200: {
          content: {
            "application/json": components["schemas"]["ClusterTopology"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ProdFlowSpec: {
      "docker-compose"?: unknown[];
    };
    DevFlowSpec: {
      /** @example backend-a:latest */
      "image-locator"?: string;
      /** @example backend-service-a */
      "service-name"?: string;
      "docker-compose"?: unknown[];
    };
    Node: {
      /** @description Unique identifier for the node. */
      id: string;
      /** @description Label for the node. */
      label?: string;
    };
    Edge: {
      /** @description The identifier of the source node of the edge. */
      source: string;
      /** @description The identifier of the target node of the edge. */
      target: string;
      /** @description Label for the edge. */
      label?: string;
    };
    ClusterTopology: {
      nodes: components["schemas"]["Node"][];
      edges: components["schemas"]["Edge"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
