name: Publish demo artifacts

on:
  push:

jobs:
  build-publish-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push voting app UI - v1
        uses: docker/build-push-action@v6
        with:
          context: ./examples/voting-app/voting-app-ui/
          file: ./examples/voting-app/voting-app-ui/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kurtosistech/demo/voting-app-ui:latest
