on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    # skip releases on forks
    if: github.repository == 'kurtosis-tech/kardinal'
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.RELEASER_TOKEN }}
          release-type: simple
          package-name: kardinal
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          include-v-in-tag: false
